AWSTemplateFormatVersion: 
Description: 
myVPC:
  Type: AWS::EC2::VPC
  Properties:
    CidrBlock: --.--.--.--/--
    EnableDnsSupport: true
    Tags:
      - Key: keyname
        Value: value
appserver:
  Type: AWS::EC2::Subnet
  Properties:
    AvailabilityZone: zone-id
    VpcId: vpc-id
    Tags:
      - Key: keyname
        Value: value
webserver:
  Type: AWS::EC2::Subnet
  Properties:
    AvailabilityZone: zone-id
    VpcId: vpc-id
    CidrBlock: --.--.--.--/--
    Tags:
      - Key: keyname
        Value: value
dbserver:
  Type: AWS::EC2::Subnet
  Properties:
    AvailabilityZone: zone-id
    VpcId: vpc-id
    CidrBlock: --.--.--.--/--
    Tags:
      - Key: keyname
        Value: value