AWSTemplateFormatVersion: 2010-09-09
Description: "This template provisions vp and subnets for our dev env"
Metadata: {}

Parameters: {}

Mappings: {}

Conditions: {}

Resources: 
  # This is the development vpc
  DevVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: DevVPC
  # This is for appserver subnet
  DevappServerSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-east-1a
      VpcId: !Ref DevVPC
      CidrBlock: 10.0.1.0/24
      Tags:
        - Key: Name
          Value: DevappServerSubnet
  # This is for webserver subnet
  DevWebServerSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-east-1b
      VpcId: !Ref DevVPC
      CidrBlock: 10.0.2.0/24
      Tags:
        - Key: Name
          Value: DevWebServerSubnet
  # This is the database subnet
  DevDbServerSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-east-1c
      VpcId: !Ref DevVPC
      CidrBlock: 10.0.3.0/24
      Tags:
        - Key: Name
          Value: DevDbServerSubnet

Outputs: {}